#state can be either "awake" or "NREM"
#brain_state: "NREM"
brain_state: "awake"
use_single_compartment_environment: True
#exc_neu_params_filename: "Ca-AdEx_neural_params.yaml"
inh_neu_params_filename: "standard_AdEx_inh_neural_params.yaml"
#exc_neu_params_filename: "standard_AdEx_exc_neural_params.yaml" 
exc_neu_params_filename: "MC-g0_like-exc_neural_params.yaml"
cf: 1.0

exc_neu_params_filename: MC-g0_like-exc_neural_params.yaml
inh_neu_params_filename: standard_AdEx_inh_neural_params.yaml
network:
  num_exc_neu_per_pop: 20
  num_exc_pop: 4
  conn_rule: "pairwise_bernoulli"
  p_conn_exc: 1.0
  p_conn_inh: 1.0
  num_poisson_generators: 20
  use_dc_exc_injectors: false
  use_dc_inh_injector: true
  use_exc_recurrency: true
  use_poisson_generators: true
contextual_poisson:
  awake:
    basic_rate: 1500.0
    poisson_weight: 0.6
    spreading_factor: 4.0
    events:
    - start_time_ms: 6000.0
      stop_time_ms: 7000.0
      target_population: 0
    - start_time_ms: 8000.0
      stop_time_ms: 9000.0
      target_population: 1
    - start_time_ms: 10000.0
      stop_time_ms: 11000.0
      target_population: 1
    - start_time_ms: 12000.0
      stop_time_ms: 13000.0
      target_population: 0
  NREM:
    basic_rate: 1500.0
    poisson_weight: 0.6
    spreading_factor: 4.0
    events:
    - start_time_ms: 10000.0
      stop_time_ms: 12000.0
      target_population: 1
    - start_time_ms: 15000.0
      stop_time_ms: 17000.0
      target_population: 0
poisson:
  NREM:
    poisson_basic_rate: 600.0
    poisson_delta: 0.0
    poisson_noise_spreading_factor: 4.0
    poisson_weight: 0.6
  awake:
    poisson_basic_rate: 600.0
    poisson_delta: 0.0
    poisson_noise_spreading_factor: 4.0
    poisson_weight: 0.6
use_single_compartment_environment: true
weights:
  NREM:
    exc_to_inh_weight: 7.0
    inh_to_exc_weight: -1.7
    inh_to_inh_weight: -1.0
    recurrent_weight: 19.0
  awake:
    exc_to_inh_weight: 7.0
    inh_to_exc_weight: -0.85
    inh_to_inh_weight: -1.0
    recurrent_weight: 9.5
dc_exc:
  amplitudes:
  - 0
  - 0
  delay: 1.0
  weight: 1.0
dc_inh:
  amplitude: 0.0
  delay: 1.0
  weight: 1.0
