brain_state: awake
cf: 1.0
contextual_poisson:
  awake:
    basic_rate: 200.0
    poisson_weight: 0.6 
    spreading_factor: 4
    start_time: 1000.
    stop_time: 2000.
    target_pop: 2
dc_exc:
  amplitudes:
  - 0
  - 0
  delay: 1.0
  weight: 1.0
dc_inh:
  amplitude: 0.0
  delay: 1.0
  weight: 1.0
exc_neu_params_filename: MC-g0_like-exc_neural_params.yaml
inh_neu_params_filename: standard_AdEx_inh_neural_params.yaml
network:
  num_exc_neu_per_pop: 20
  num_exc_pop: 4
  num_poisson_generators: 20
  use_dc_exc_injectors: false
  use_dc_inh_injector: true
  use_exc_recurrency: true
  use_poisson_generators: true
poisson:
  NREM:
    poisson_basic_rate: 600.0
    poisson_delta: 0.0
    poisson_noise_spreading_factor: 4.0
    poisson_weight: 0.6
  awake:
    poisson_basic_rate: 600.0
    poisson_delta: 0.0
    poisson_noise_spreading_factor: 4.0
    poisson_weight: 0.6
use_single_compartment_environment: true
weights:
  NREM:
    exc_to_inh_weight: 7.0
    inh_to_exc_weight: -1.7
    inh_to_inh_weight: -1.0
    recurrent_weight: 19.0
  awake:
    exc_to_inh_weight: 7.0
    inh_to_exc_weight: -0.85
    inh_to_inh_weight: -1.0
    recurrent_weight: 9.5
